version: "3.9"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3002:3002"
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3001"
