version: "3"
services:
  frontend:
    build: ./ui
    image: "reactapp:1.0.0"
    networks:
      - sub-etha
  backend:
    build: ./server
    image: "expressapp:1.0.0"
    networks:
      - sub-etha
  revproxy:
    build: ./nginx
    image: "reverseproxy:1.0.0"
    networks:
      - sub-etha
    ports:
      - "3000:80"
networks:
  sub-etha:
