version: "3"
services:
  frontend:
    build: ./ui
    image: "miketmoore/ui:1.0.0"
    networks:
      - miketmoore/network
  backend:
    build: ./server
    image: "miketmoore/api:1.0.0"
    networks:
      - miketmoore/network
  reverseproxy:
    build: ./nginx
    image: "miketmoore/reverseproxy:1.0.0"
    networks:
      - miketmoore/network
    ports:
      - "3000:80"
networks:
  miketmoore/network:
